# Generated by Django 3.0.6 on 2020-05-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200519_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayPic',
            field=models.ImageField(blank=True, upload_to='displayPics'),
        ),
    ]
