# Generated by Django 3.0.6 on 2020-05-26 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0012_auto_20200526_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friendRequests',
            field=models.ManyToManyField(blank=True, related_name='friendRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
