# Generated by Django 3.0.6 on 2020-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_profile_friendrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
