# Generated by Django 3.0.6 on 2020-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_education_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='ongoing',
            field=models.BooleanField(blank=True),
        ),
    ]
