# Generated by Django 3.0.6 on 2020-05-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20200527_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='description',
            new_name='about',
        ),
    ]
