# Generated by Django 3.0.7 on 2020-06-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20200527_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayPic',
        ),
    ]
