# Generated by Django 3.0.7 on 2020-06-13 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0017_remove_profile_displaypic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('birthdate', models.DateField(blank=True)),
                ('education', models.ManyToManyField(blank=True, related_name='education', to='hello.Education')),
                ('friendRequests', models.ManyToManyField(blank=True, related_name='friendRequests', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='projects', to='hello.Project')),
                ('skills', models.ManyToManyField(blank=True, related_name='skills', to='hello.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(blank=True, related_name='work', to='hello.Work')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
