# Generated by Django 3.0.7 on 2020-06-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20200613_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='ongoing',
        ),
    ]
