# Generated by Django 3.0.7 on 2020-06-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_remove_work_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprofile',
            name='birthdate',
        ),
    ]
