# Generated by Django 3.0.7 on 2020-06-14 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0020_remove_workprofile_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('shortAbout', models.CharField(blank=True, max_length=200, null=True)),
                ('longAbout', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('categorys', models.ManyToManyField(blank=True, related_name='categorys', to='hello.Post')),
                ('education', models.ManyToManyField(blank=True, related_name='education', to='hello.Education')),
                ('friendRequests', models.ManyToManyField(blank=True, related_name='friendRequests', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='homePosts', to='hello.Post')),
                ('projects', models.ManyToManyField(blank=True, related_name='projects', to='hello.Project')),
                ('skills', models.ManyToManyField(blank=True, related_name='skills', to='hello.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(blank=True, related_name='work', to='hello.Work')),
            ],
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='friendRequests',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workprofile',
            name='work',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='WorkProfile',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='hello.Post'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
