# Generated by Django 3.0.7 on 2020-06-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20200614_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='caption',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
