# Generated by Django 3.0.7 on 2020-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_auto_20200614_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categorys',
            field=models.ManyToManyField(blank=True, related_name='categorys', to='hello.Category'),
        ),
    ]
